version: "3.3"
services:
  app1:
    build: streamlit_apps/app1
    ports:
      - "5001:8501"
  app2:
    build: streamlit_apps/app2
    ports:
      - "5002:8501"
  nginx:
    build: nginx_docker
    ports:
        - "8080:80"
    depends_on:
        - app1
        - app2